---
# tasks file for postgresql-replication-standby
- meta: flush handlers

- name: ensure rsync presence
  apt:
    pkg: rsync
    state: latest

- name: stop postgresql service
  service:
    name: postgresql
    state: stopped

- name: empty data directory
  file:
    path: "{{ postgresql_data_dir }}"
    state: "{{ item }}"
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
    - absent
    - directory

- name: Create base backup
  command: "pg_basebackup -h {{ postgresql_master_host }} -D {{ postgresql_data_dir }} -P -U replication --xlog-method=stream -R"
  
- name: start postgresql service
  service:
    name: postgresql
    state: started
